# Root directory of the project
root_dir = "./"

# File extensions to watch
watch_ext = ["go", "html", "yaml", "json"]

# Build command
cmd = "go build -o ./tmp/main ./"

# Path to the built binary
bin = "./tmp/main"

# Include directories to watch for changes
include_dir = [
    "cmd/app",
    "pkg"
]

# Exclude directories
exclude_dir = [
    "tmp"
]
