export type Vehicle = {
    id: number;
    vin: string;
    licensePlateNumber: string;
    make: string;
    year: string;
    color: string;
    carType: string;
    carPicture: File | null;
    bollo: File | null;
    insurance: File | null;
    libre: File | null;
    ownerId: number;
    createdAt: string;
    updatedAt: string;
    driverId: number;
    driver: {
      id: number;
      createdAt: string;
      updatedAt: string;
      userId: number;
      user: {
        id: number;
        createdAt: string;
        updatedAt: string;
        firstName: string;
        lastName: string;
        email: string;
        phoneNumber: string;
        isOnline: boolean;
        profilePicture: string;
        isVerified: boolean;
        lastLoginDate: string;
        socketId: string | null;
        roles: string;
      };
      driverLicense: string;
      status: string;
      drivingLicensePath: string;
      nationalIdPath: string;
      insuranceDocPath: string | null;
      otherFilePath: string | null;
    };
  };
