info:
  contact: {}
paths:
  /:
    get:
      description: This function initializes and registers all the API routes for
        users, roles, permissions, and role permissions.
      responses: {}
      summary: Initialize routes
      tags:
      - Initialization
  /api/permissions:
    post:
      description: Defines all the routes related to permission operations such as
        creating, updating, deleting, and associating roles with permissions.
      responses: {}
      summary: Register permission routes
      tags:
      - Permission
  /api/role_permissions:
    post:
      description: Defines all the routes related to managing role-permission associations.
      responses: {}
      summary: Register role permission routes
      tags:
      - RolePermission
  /api/roles:
    post:
      description: Defines all the routes related to role operations such as creating,
        updating, and deleting roles.
      responses: {}
      summary: Register role routes
      tags:
      - Role
  /api/user:
    post:
      description: Defines all the routes related to user operations such as registration,
        login, token refresh, etc.
      responses: {}
      summary: Register user routes
      tags:
      - User
swagger: "2.0"
