name: Go Linting

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.19' # Specify your Go version

    - name: Install golangci-lint
      run: |
        curl -sSfL https://github.com/golangci/golangci-lint/releases/download/v1.52.2/golangci-lint-1.52.2-linux-amd64.tar.gz | tar -xzv -C /tmp
        mv /tmp/golangci-lint-*/golangci-lint /usr/local/bin

    - name: Run golangci-lint on Backend
      run: |
        cd Backend # Change to the Backend directory
        golangci-lint run --config .golangci.yml # This assumes you have a golangci-lint config file in the Backend directory
